### ISSUE TITLE
What is the criterion for a paper to be in the list?

### ISSUE THREAD

**Issue by Serjio42** [ghimiredhikura/Awasome-Pruning#3]
Hello. As I see in the description, your papers list is 

> inspired by [he-y/Awesome-Pruning](https://github.com/he-y/Awesome-Pruning)

The question is what is the common criterion for all the participants to getting into the list. The list looks like not so comprehensive in comparison with https://github.com/he-y/Awesome-Pruning .

**Comment by ghimiredhikura** [comment]
Hi @Serjio42, 

I am doing research in the field, therefore it's like a collection of papers that I go through. The plan is to collect many papers that are practical and influential. Yes, you can say it is just yet another collection similar to [he-y/Awesome-Pruning](https://github.com/he-y/Awesome-Pruning). I am interested to collect papers not only from conferences but from journals too. Again, would be nice to collect pruning tools, tutorials, and invited talks at the conferences. 

So you are welcome to include your papers and others as well.
